name: CI
  
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', 'pypy-2.7', 'pypy-3.7', 'pyston']
        os: [ubuntu-latest]
        architecture: ["x64"]
        include:
          - python-version: '3.4'
            os: ubuntu-18.04
            architecture: "x64"
          - python-version: '3.9'
            os: macos-latest
            architecture: "x64"
          - python-version: '3.9'
            os: windows-latest
            architecture: "x64"
          - python-version: '3.9'
            os: windows-latest
            architecture: "x86"
          - python-version: '2.7'
            os: windows-latest
            architecture: "x86"

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodule
      run: |
        git submodule init
        git submodule update
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version != 'pyston' }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Set up Pyston
      if: ${{ matrix.python-version == 'pyston' }}
      run: |
        wget -O pyston.deb https://github.com/pyston/pyston/releases/download/pyston_2.3.2/pyston_2.3.2_20.04.deb
        sudo apt update
        sudo apt install -y ./pyston.deb
        sudo ln -sf pyston /usr/bin/python
        sudo chown -RH $(whoami) $(python -c 'import os,inspect;print(os.path.dirname(inspect.getfile(inspect)))')
        sudo chown -hRH $(whoami) /usr/bin
    - name: "Install Visual C++ for Python 2.7"
      if: ${{ matrix.os == 'windows-latest' && matrix.python-version == '2.7' }}
      run: |
        curl -L -O https://github.com/reider-roque/sulley-win-installer/raw/master/VCForPython27.msi
        msiexec /i VCForPython27.msi /qn
    #     choco install vcpython27 -f -y
    - name: "Install mingw-w64-i686-gcc"
      if: ${{ matrix.os == 'windows-latest' && matrix.architecture == 'x86' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        path-type: inherit
        install: mingw-w64-i686-gcc
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest wheel pybind11
    # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install
      if: ${{ matrix.os != 'windows-latest' || matrix.architecture != 'x86' }}
      run: |
        python -m pip install .
    - name: Build wheel (Win32)
      if: ${{ matrix.os == 'windows-latest' && matrix.architecture == 'x86' }}
      shell: msys2 {0}
      run: |
        python -m pip install .
    - name: Test
      run: |
        pytest -v test -s
